### ISSUE TITLE
Something wrong with php file, incomplete line

### ISSUE THREAD

**Issue by bmentink** [nilwes/toitglamp#1]
Hi,
I am trying to duplicate this project, but notice the $sql line in the .php file is incomplete, all I have is:

$sql = mysqli_query($conn, "INSERT INTO THPData (Temp, Hum, Press) VALUES (" . $temp . "," . $hum$

The end of the line is incomplete: Can you please correct this please?

**Comment by nilwes** [comment]
Hi,

It should be corrected now. Thanks for noticing it. A copy-paste error from Nano.

**Comment by bmentink** [comment]
Cool, Thanks ...
